name: Run tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Lint with Ruff
        run: uv run --frozen ruff check

      - name: Check with mypy
        run: uv run --frozen mypy --strict .

      - name: Run tests
        run: uv run --frozen python -m unittest
